### ISSUE TITLE
usage of the release

### ISSUE THREAD

**Issue by bertvannuffelen** [FundingCircle/fc4-framework#97] opened 2018-11-20 08:32 UTC
Hi,

I wanted to test the release. I downloaded and unpacked it on my linux box.
and then copied one of the tests files and tried to render it. But the tool gets stuck and does not produce any result.

``` 
cp ../../tool/test/data/model\ \(valid\)/systems/division-a/middle.yaml .
./fc4-render middle.yaml 
```

What do I miss? kr Bert

**Comment by aviflax** [comment] 2018-11-20 22:01
Hi Bert, my apologies! I have a few fixes for this that should be merged soon (and each merge results in a new release with new download packages). I’ll let you know once they’re merged and the new release is ready. In the meantime, you’re welcome to try [this prerelease](https://github.com/FundingCircle/fc4-framework/releases/tag/prerelease_publish-prereleases) — the Mac download, at least, works on my machine ;)

If you’re curious about the problems their solutions, feel free to check out #95 and #98.

Also, a few notes on your test commands:

* The YAML file you’re copying, `middle.yaml`, is not an FC4 diagram
  * (which, at the moment, is synonomous with a [Structurizr Express](https://structurizr.com/express) diagram)
  * it’s a file describing a single software system; part of a set of files that together define a model of an entire system landscape, or maybe even multiple landscapes. This is a new DSL that I’m working on, but isn’t yet fully supported. (I’d love your feedback on #73 if you’re interested.)
  * As an alternative, you can use `<project_root>/tool/test/data/structurizr/express/diagram_valid_messy.yaml`
* `fc4-render` isn’t meant to be used directly; it’s meant to be invoked via the main `fc4` command, which you’d invoke like: `fc4 render path/to/diagram.yaml`
  * If you’d still like to run `fc4-render` directly, for debugging or maybe for the shorter execution times, you’ll need to pipe input to it and save its output yourself, like: `cat path/to/diagram.yaml | fc4-render > diagram.png`

**Comment by aviflax** [comment] 2018-11-21 17:35
Hi Bert, those fixes have been merged and there’s [a fresh new release](https://github.com/FundingCircle/fc4-framework/releases/tag/master_2018-11-21_650) — I’d love to hear whether it works for you. If it doesn’t, please share the command you’re using, your OS, your Java install, and anything else you think might help me reproduce.

**Comment by bertvannuffelen** [comment] 2018-11-22 23:02
Hi Avi,

thanks for the update. There seem to be still some issues left:

```
root@2284d6376a66:/data/fc4# fc4 render diagram_valid_cleaned.yaml 
bash: fc4: command not found
root@2284d6376a66:/data/fc4# ./fc4 render diagram_valid_cleaned.yaml 
invoking renderer...
Exception in thread "main" java.io.IOException: Cannot run program "fc4-render": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at clojure.java.shell$sh.invokeStatic(shell.clj:113)
	at clojure.java.shell$sh.doInvoke(shell.clj:79)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at fc4.integrations.structurizr.express.render$render.invokeStatic(render.clj:27)
	at fc4.integrations.structurizr.express.render$render.invoke(render.clj:16)
	at fc4.cli.render$render.invokeStatic(render.clj:15)
	at fc4.cli.render$render.invoke(render.clj:13)
	at fc4.cli.render$_main.invokeStatic(render.clj:34)
	at fc4.cli.render$_main.doInvoke(render.clj:19)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at fc4.cli.fc4$_main.invokeStatic(fc4.clj:32)
	at fc4.cli.fc4$_main.doInvoke(fc4.clj:21)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at fc4.cli.fc4.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 17 more
root@2284d6376a66:/data/fc4# cat  
.README.md.swp              diagram.png                 fc4                         fc4.jar                     middle.yaml                 
README.md                   diagram_valid_cleaned.yaml  fc4-render                  front.yaml                  
root@2284d6376a66:/data/fc4# cat diagram_valid_cleaned.yaml |fc4-render > diagram.yml
bash: fc4-render: command not found
root@2284d6376a66:/data/fc4# cat diagram_valid_cleaned.yaml |./fc4-render > diagram.yml
launching browser...
loading Structurizr Express from https://structurizr.com/express?autoLayout=false...
setting YAML and updating diagram...
calling export function...
(node:28) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'crop' of undefined
    at Structurizr.DiagramScripting.exportCurrentDiagramToPNG (https://structurizr.com/static/js/structurizr-scripting-diagram.js?v=1373:13:59)
    at __puppeteer_evaluation_script__:2:34
    at ExecutionContext.evaluateHandle (/snapshot/root/project/tool/renderer/node_modules/puppeteer-core/lib/ExecutionContext.js:106:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I run it within one of the Docker images you have defined in this project.
I think I use this Dockerfile for the container image
```
FROM node:10.13.0-stretch

LABEL maintainer="Avi Flax <avi.flax@fundingcircle.com>"
LABEL description="Node 10 (LTS), Clojure 1.9, and Chromium 70 on Debian Stretch"

ENV JRE_VERSION=8u181-b13-2~deb9u1
ENV CLOJURE_VERSION=1.9.0.394
ENV CHROMIUM_VERSION=70.0.3538.67-1~deb9u1

WORKDIR /tmp

# Install dependencies of the Renderer and Clojure
# We’re including rlwrap just because it’s handy in case we need to run a REPL
# in a container, for debugging.
RUN apt-get update -yq
RUN apt-get install -yq chromium=$CHROMIUM_VERSION openjdk-8-jre=$JRE_VERSION rlwrap

# Install Clojure
RUN wget -q https://download.clojure.org/install/linux-install-$CLOJURE_VERSION.sh \
      && chmod +x linux-install-$CLOJURE_VERSION.sh \
      && ./linux-install-$CLOJURE_VERSION.sh
```

and start the docker with 
`sudo docker run -it --rm --entrypoint bash -v $PWD:/data fc4base
`

**Comment by aviflax** [comment] 2018-11-26 15:21
Hi Bert,

I’m sorry you’re still having trouble. Also, sorry for my tardy response; I was offline for the Thanksgiving holiday here in the USA.

WRT the error `Cannot run program "fc4-render"` I believe this is happening because `fc4-render` is not in a dir that’s in your shell’s PATH variable. This requirement is mentioned in the readme but probably not prominently enough — sorry about that. (It just occurred to me that I _might_ be able to embed the renderer executable in the main jar file… I’ll look into that.) So maybe try either moving the files in the distribution archive into such a dir, or modifying that var?

As for the runtime environment, I’m glad you explained it so thoroughly. I’m surprised you’re using Docker, as the tool isn’t meant (currently) to be run within a Docker container, as (currently) it needs access to the user’s system clipboard, which is overly complicated with Docker. I’m _also_ surprised that you’re using that particular Dockerfile, which I believe is in the dir `.circleci/images/tool/` — this image is intended for testing and packaging the tool, not for running it.

That said, certainly the `fc4 render` command _should_ work just fine within a container using that image; I do it myself sometimes as a manual test. I’d think you should be able to download and extract the archive, make sure the files are accessible via the shell’s PATH, and then it _should_ work.

That said, I’m curious why you’re trying to run the tool within Docker? I’d love to understand your use case so I can consider whether perhaps the tool should support this case better.

Thanks!
Avi

**Comment by aviflax** [comment] 2018-11-27 16:18
Thanks Bert, that makes sense!

In a few hours I’ll whip up a working example that you can try out and we can then add to the docs. Thanks for your patience!

**Comment by aviflax** [comment] 2018-11-27 20:02
@bertvannuffelen I just opened #114 with an example Dockerfile that works for me; maybe give it a try?

**Comment by aviflax** [comment] 2019-03-14 17:47
Closing as stale.

**Closed by aviflax** 2019-03-14 17:47 UTC
Labels: bug, documentation
